# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/Custom/Custom_Container_1.qml) \
        $$quote($$BASEDIR/assets/Custom/Custom_MainContainer.qml) \
        $$quote($$BASEDIR/assets/Images/Image_AbWheelRollOuts.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellBackSquats.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellBenchFrontSquats.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellDeadlifts.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellFrontSquats.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellGoodMornings.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellHipThrust.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellRackPulls.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellStiffLegDeadlifts.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BicepsCurlEZBar.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BicepsCurlMachine.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_CableBarTricepsPushdown.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_CableTricepsRopePushdowns.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_ChestDips.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_ClockPushUps.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_DeficitDeadlifts.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_DumbbellLungess.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_FlatBarbellChestPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_FlatCableFly.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_FlatDumbbellChestPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_FlatDumbbellFly.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_GluteHamRaise.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_GobletSquats.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_InclineBarbellChestPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_InclineBenchDumbbellRows.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_InclineDumbbellChestPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_InclineDumbbellFly.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_LegExtensions.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_LegPressMachine.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_LyingBarbellTricepsExtensions.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_LyingDumbbellTricepsExtensions.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_LyingHamstringCurls.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_LyingInclineBarbellBicepsCurl.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_NarrowUnderhandGripLatPulldown.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_OneArmDumbbellRowOnBench.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_OneLegStiffDeadlift.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_OverhandGripBarbellBentOverRows.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_ReverseGripOneArmCableTricepsPushdowns.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedBarbbellBicepsCurl.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedBarbellArnoldPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedBarbellCalfRaises.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedBarbellShoulderPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedCableRow.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedDumbbellBicepsHammerCurls.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedDumbbellShoulderPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedDumbbellTricepsExtensions.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedInclineDumbbellBicepsCurl.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedMachineChestPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedOverheadBarbellPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedTwoArmOverheadDumbbellTricepsExtensions.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SingleLegBarbellHipThrust.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SingleLegDumbbellSplitSquat.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingAlternateDumbbellBicepsCurls.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingBarbellFrontRaises.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingBarbellPushPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingBentOverLateralRaises.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingBicepsCableCurl.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingCableBarLatPushdown.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingCableRearDeltFly.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingCableRearDeltRopePulls.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingCableRopeHammerCurl.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingCalfRaisesMachine.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingDumbbellBicepsHammerCurls.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingDumbbellFrontRaises.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingDumbbellInnerBicepsCurl.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingDumbbellLateralRaises.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingDumbbellShoulderPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingFrontBarbellShrugs.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingOneArmDumbbellShoulderPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingOverheadBarbellPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingWideGripUprightRows.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SumoDeadlift.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_TBarRows.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_ThighAbductor.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_ThighAdductor.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_TricepsDips.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_WeightTricepsDips.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_WeightWideGripOverhandChinUps.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_WideGripOverhandChinUps.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_WideGripStandingBarbellBicepsCurl.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_WideGripStandingEZBarCur.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_WideOverhandGripLatPulldown.jpg) \
        $$quote($$BASEDIR/assets/Pages/Page_Exercis.qml) \
        $$quote($$BASEDIR/assets/Pages/Page_Exercises.qml) \
        $$quote($$BASEDIR/assets/Pages/Page_Weeks.qml) \
        $$quote($$BASEDIR/assets/Sheets/Sheets_OtherWeeks.qml) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercise_.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_Barbell Deadlifts.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_BarbellBackSquats.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_BarbellBenchFrontSquats.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_BarbellFrontSquats.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_BarbellGoodMornings.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_BarbellHipThrust.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_BarbellStiffLegDeadlifts.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_BicepsCurlEZBar.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_BicepsCurlMachine.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_DumbbellLungess.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_GluteHamRaise.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_GobletSquats.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_LegExtensions.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_LegPressMachine.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_LyingHamstringCurls.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_LyingInclineBarbellBicepsCurl.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_OneLegStiffDeadlift.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_SeatedBarbbellBicepsCurl.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_SeatedBarbellArnoldPress.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_SeatedBarbellShoulderPress.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_SeatedDumbbellBicepsHammerCurls.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_SeatedDumbbellShoulderPress.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_SeatedInclineDumbbellBicepsCurl.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_SingleLegBarbellHipThrust.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_SingleLegDumbbellSplitSquat.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_StandingAlternateDumbbellBicepsCurls.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_StandingBarbellFrontRaises.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_StandingBarbellPushPress.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_StandingBentOverLateralRaises.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_StandingBicepsCableCurl.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_StandingCableRearDeltFly.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_StandingCableRopeHammerCurl.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_StandingDumbbellBicepsHammerCurls.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_StandingDumbbellFrontRaises.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_StandingDumbbellInnerBicepsCurl.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_StandingDumbbellLateralRaises.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_StandingDumbbellShoulderPress.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_StandingOneArmDumbbellShoulderPress.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_StandingOverheadBarbellPress.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_StandingWideGripUprightRows.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_SumoDeadlift.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_ThighAbductor.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_ThighAdductor.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_WideGripStandingBarbellBicepsCurl.json) \
        $$quote($$BASEDIR/assets/XML + JSON/JSON/Excercises/Excercise_WideGripStandingEZBarCurl.json) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_01.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_02.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_03.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_04.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_05.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_06.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_07.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_08.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_09.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_10.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_11.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_12.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_13.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_14.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_15.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_16.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_17.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_18.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_19.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_20.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_21.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_22.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_23.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_24.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_25.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_26.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_27.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_28.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_29.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_30.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_31.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_32.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_33.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_34.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_35.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_36.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_37.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_38.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_39.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_40.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_41.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_42.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_43.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_44.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Days/Day_45.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Weeks/Week_01.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Weeks/Week_02.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Weeks/Week_03.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Weeks/Week_04.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Weeks/Week_05.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Weeks/Week_06.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Weeks/Week_07.xml) \
        $$quote($$BASEDIR/assets/XML + JSON/XML/Weeks/Week_08.xml) \
        $$quote($$BASEDIR/assets/main.qml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/Settings/settings.cpp) \
        $$quote($$BASEDIR/src/Timer/timer.cpp) \
        $$quote($$BASEDIR/src/WebImageView/webimageview.cpp) \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/main.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/Settings/settings.hpp) \
        $$quote($$BASEDIR/src/Timer/timer.hpp) \
        $$quote($$BASEDIR/src/WebImageView/webimageview.hpp) \
        $$quote($$BASEDIR/src/applicationui.hpp)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../src/Settings/*.c) \
        $$quote($$BASEDIR/../src/Settings/*.c++) \
        $$quote($$BASEDIR/../src/Settings/*.cc) \
        $$quote($$BASEDIR/../src/Settings/*.cpp) \
        $$quote($$BASEDIR/../src/Settings/*.cxx) \
        $$quote($$BASEDIR/../src/Timer/*.c) \
        $$quote($$BASEDIR/../src/Timer/*.c++) \
        $$quote($$BASEDIR/../src/Timer/*.cc) \
        $$quote($$BASEDIR/../src/Timer/*.cpp) \
        $$quote($$BASEDIR/../src/Timer/*.cxx) \
        $$quote($$BASEDIR/../src/WebImageView/*.c) \
        $$quote($$BASEDIR/../src/WebImageView/*.c++) \
        $$quote($$BASEDIR/../src/WebImageView/*.cc) \
        $$quote($$BASEDIR/../src/WebImageView/*.cpp) \
        $$quote($$BASEDIR/../src/WebImageView/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/*.js) \
        $$quote($$BASEDIR/../assets/Custom/*.qs) \
        $$quote($$BASEDIR/../assets/Images/*.qml) \
        $$quote($$BASEDIR/../assets/Images/*.js) \
        $$quote($$BASEDIR/../assets/Images/*.qs) \
        $$quote($$BASEDIR/../assets/Pages/*.qml) \
        $$quote($$BASEDIR/../assets/Pages/*.js) \
        $$quote($$BASEDIR/../assets/Pages/*.qs) \
        $$quote($$BASEDIR/../assets/Sheets/*.qml) \
        $$quote($$BASEDIR/../assets/Sheets/*.js) \
        $$quote($$BASEDIR/../assets/Sheets/*.qs) \
        $$quote($$BASEDIR/../assets/XML + JSON/*.qml) \
        $$quote($$BASEDIR/../assets/XML + JSON/*.js) \
        $$quote($$BASEDIR/../assets/XML + JSON/*.qs) \
        $$quote($$BASEDIR/../assets/XML + JSON/JSON/*.qml) \
        $$quote($$BASEDIR/../assets/XML + JSON/JSON/*.js) \
        $$quote($$BASEDIR/../assets/XML + JSON/JSON/*.qs) \
        $$quote($$BASEDIR/../assets/XML + JSON/JSON/Excercises/*.qml) \
        $$quote($$BASEDIR/../assets/XML + JSON/JSON/Excercises/*.js) \
        $$quote($$BASEDIR/../assets/XML + JSON/JSON/Excercises/*.qs) \
        $$quote($$BASEDIR/../assets/XML + JSON/XML/*.qml) \
        $$quote($$BASEDIR/../assets/XML + JSON/XML/*.js) \
        $$quote($$BASEDIR/../assets/XML + JSON/XML/*.qs) \
        $$quote($$BASEDIR/../assets/XML + JSON/XML/Days/*.qml) \
        $$quote($$BASEDIR/../assets/XML + JSON/XML/Days/*.js) \
        $$quote($$BASEDIR/../assets/XML + JSON/XML/Days/*.qs) \
        $$quote($$BASEDIR/../assets/XML + JSON/XML/Weeks/*.qml) \
        $$quote($$BASEDIR/../assets/XML + JSON/XML/Weeks/*.js) \
        $$quote($$BASEDIR/../assets/XML + JSON/XML/Weeks/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}_cs.ts) \
    $$quote($${TARGET}.ts)
