# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/Custom/ActionItems/Custom_ActionItem_01.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/Custom_ActionItem_02.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/Custom_ActionItem_03.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Custom_MainContainer.qml) \
        $$quote($$BASEDIR/assets/Custom/Headers/Custom_Header_01.qml) \
        $$quote($$BASEDIR/assets/Custom/ListItemComponents/Custom_ListItemComponent_01.qml) \
        $$quote($$BASEDIR/assets/Custom/ListItemComponents/Custom_ListItemComponent_02.qml) \
        $$quote($$BASEDIR/assets/Custom/ListViews/Custom_ListView_01.qml) \
        $$quote($$BASEDIR/assets/Images/App/finished_gold.png) \
        $$quote($$BASEDIR/assets/Images/App/finished_shadow.png) \
        $$quote($$BASEDIR/assets/Images/Image_AbWheelRollOuts.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellBackSquats.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellBenchFrontSquats.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellDeadlifts.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellFrontSquats.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellGoodMornings.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellHipThrust.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellRackPulls.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BarbellStiffLegDeadlifts.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BicepsCurlEZBar.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_BicepsCurlMachine.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_CableBarTricepsPushdown.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_CableTricepsRopePushdowns.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_ChestDips.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_ClockPushUps.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_DeficitDeadlifts.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_DumbbellLungess.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_FlatBarbellChestPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_FlatCableFly.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_FlatDumbbellChestPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_FlatDumbbellFly.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_GluteHamRaise.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_GobletSquats.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_InclineBarbellChestPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_InclineBenchDumbbellRows.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_InclineDumbbellChestPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_InclineDumbbellFly.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_LegExtensions.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_LegPressMachine.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_LyingBarbellTricepsExtensions.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_LyingDumbbellTricepsExtensions.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_LyingHamstringCurls.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_LyingInclineBarbellBicepsCurl.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_NarrowUnderhandGripLatPulldown.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_OneArmDumbbellRowOnBench.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_OneLegStiffDeadlift.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_OverhandGripBarbellBentOverRows.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_ReverseGripOneArmCableTricepsPushdowns.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedBarbbellBicepsCurl.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedBarbellArnoldPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedBarbellCalfRaises.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedBarbellShoulderPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedCableRow.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedDumbbellBicepsHammerCurls.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedDumbbellShoulderPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedDumbbellTricepsExtensions.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedInclineDumbbellBicepsCurl.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedMachineChestPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedOverheadBarbellPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SeatedTwoArmOverheadDumbbellTricepsExtensions.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SingleLegBarbellHipThrust.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SingleLegDumbbellSplitSquat.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingAlternateDumbbellBicepsCurls.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingBarbellFrontRaises.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingBarbellPushPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingBentOverLateralRaises.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingBicepsCableCurl.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingCableBarLatPushdown.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingCableRearDeltFly.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingCableRearDeltRopePulls.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingCableRopeHammerCurl.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingCalfRaisesMachine.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingDumbbellBicepsHammerCurls.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingDumbbellFrontRaises.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingDumbbellInnerBicepsCurl.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingDumbbellLateralRaises.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingDumbbellShoulderPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingFrontBarbellShrugs.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingOneArmDumbbellShoulderPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingOverheadBarbellPress.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_StandingWideGripUprightRows.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_SumoDeadlift.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_TBarRows.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_ThighAbductor.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_ThighAdductor.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_TricepsDips.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_WeightTricepsDips.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_WeightWideGripOverhandChinUps.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_WideGripOverhandChinUps.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_WideGripStandingBarbellBicepsCurl.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_WideGripStandingEZBarCur.jpg) \
        $$quote($$BASEDIR/assets/Images/Image_WideOverhandGripLatPulldown.jpg) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Data/Database.db) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Data/MaxRepExcercise.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Data/Plans.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_01.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_02.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_03.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_04.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_05.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_06.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_07.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_08.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_09.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_10.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_11.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_12.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_13.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_14.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_15.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_16.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_17.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_18.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_19.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_20.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_21.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_22.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_23.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_24.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_25.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_26.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_27.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_28.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_29.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_30.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_31.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_32.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_33.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_34.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_35.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_36.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_37.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_38.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_39.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_40.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_41.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_42.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_43.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_44.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Days/Plan_01/Day_45.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_BarbellBackSquats.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_BarbellBenchFrontSquats.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_BarbellDeadlifts.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_BarbellFrontSquats.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_BarbellGoodMornings.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_BarbellHipThrust.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_BarbellStiffLegDeadlifts.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_BicepsCurlEZBar.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_BicepsCurlMachine.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_DumbbellLungess.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_GluteHamRaise.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_GobletSquats.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_LegExtensions.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_LegPressMachine.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_LyingHamstringCurls.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_LyingInclineBarbellBicepsCurl.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_OneLegStiffDeadlift.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_SeatedBarbbellBicepsCurl.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_SeatedBarbellArnoldPress.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_SeatedBarbellShoulderPress.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_SeatedDumbbellBicepsHammerCurls.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_SeatedDumbbellShoulderPress.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_SeatedInclineDumbbellBicepsCurl.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_SingleLegBarbellHipThrust.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_SingleLegDumbbellSplitSquat.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_StandingAlternateDumbbellBicepsCurls.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_StandingBarbellFrontRaises.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_StandingBarbellPushPress.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_StandingBentOverLateralRaises.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_StandingBicepsCableCurl.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_StandingCableRearDeltFly.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_StandingCableRopeHammerCurl.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_StandingDumbbellBicepsHammerCurls.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_StandingDumbbellFrontRaises.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_StandingDumbbellInnerBicepsCurl.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_StandingDumbbellLateralRaises.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_StandingDumbbellShoulderPress.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_StandingOneArmDumbbellShoulderPress.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_StandingOverheadBarbellPress.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_StandingWideGripUprightRows.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_SumoDeadlift.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_ThighAbductor.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_ThighAdductor.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_WideGripStandingBarbellBicepsCurl.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Excercises/Plan_01/Excercise_WideGripStandingEZBarCurl.json) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Plans/Plan_01.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Weeks/Plan_01/Week_01.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Weeks/Plan_01/Week_02.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Weeks/Plan_01/Week_03.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Weeks/Plan_01/Week_04.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Weeks/Plan_01/Week_05.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Weeks/Plan_01/Week_06.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Weeks/Plan_01/Week_07.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Weeks/Plan_01/Week_08.xml) \
        $$quote($$BASEDIR/assets/JavaScripts/JavaScript_AddMovements.js) \
        $$quote($$BASEDIR/assets/JavaScripts/JavaScript_Workouts.js) \
        $$quote($$BASEDIR/assets/NavigationPanels/NavigationPane_MyRecords.qml) \
        $$quote($$BASEDIR/assets/NavigationPanels/NavigationPane_Workouts.qml) \
        $$quote($$BASEDIR/assets/Pages/Page_AddNewRecords.qml) \
        $$quote($$BASEDIR/assets/Pages/Page_Exercis.qml) \
        $$quote($$BASEDIR/assets/Pages/Page_Exercises.qml) \
        $$quote($$BASEDIR/assets/Pages/Page_MyRecords.qml) \
        $$quote($$BASEDIR/assets/Pages/Page_OtherWeeks.qml) \
        $$quote($$BASEDIR/assets/Pages/Page_Workouts.qml) \
        $$quote($$BASEDIR/assets/Sheets/Sheet_AddNewRecords.qml) \
        $$quote($$BASEDIR/assets/Sheets/Sheets_OtherWeeks.qml) \
        $$quote($$BASEDIR/assets/main.qml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/Settings/settings.cpp) \
        $$quote($$BASEDIR/src/SqlDatabase/sqldatabase.cpp) \
        $$quote($$BASEDIR/src/Timer/timer.cpp) \
        $$quote($$BASEDIR/src/WebImageView/webimageview.cpp) \
        $$quote($$BASEDIR/src/XmlReader/xmlreader.cpp) \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/main.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/Settings/settings.hpp) \
        $$quote($$BASEDIR/src/SqlDatabase/sqldatabase.hpp) \
        $$quote($$BASEDIR/src/Timer/timer.hpp) \
        $$quote($$BASEDIR/src/WebImageView/webimageview.hpp) \
        $$quote($$BASEDIR/src/XmlReader/xmlreader.hpp) \
        $$quote($$BASEDIR/src/applicationui.hpp)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../src/Settings/*.c) \
        $$quote($$BASEDIR/../src/Settings/*.c++) \
        $$quote($$BASEDIR/../src/Settings/*.cc) \
        $$quote($$BASEDIR/../src/Settings/*.cpp) \
        $$quote($$BASEDIR/../src/Settings/*.cxx) \
        $$quote($$BASEDIR/../src/SqlDatabase/*.c) \
        $$quote($$BASEDIR/../src/SqlDatabase/*.c++) \
        $$quote($$BASEDIR/../src/SqlDatabase/*.cc) \
        $$quote($$BASEDIR/../src/SqlDatabase/*.cpp) \
        $$quote($$BASEDIR/../src/SqlDatabase/*.cxx) \
        $$quote($$BASEDIR/../src/Timer/*.c) \
        $$quote($$BASEDIR/../src/Timer/*.c++) \
        $$quote($$BASEDIR/../src/Timer/*.cc) \
        $$quote($$BASEDIR/../src/Timer/*.cpp) \
        $$quote($$BASEDIR/../src/Timer/*.cxx) \
        $$quote($$BASEDIR/../src/WebImageView/*.c) \
        $$quote($$BASEDIR/../src/WebImageView/*.c++) \
        $$quote($$BASEDIR/../src/WebImageView/*.cc) \
        $$quote($$BASEDIR/../src/WebImageView/*.cpp) \
        $$quote($$BASEDIR/../src/WebImageView/*.cxx) \
        $$quote($$BASEDIR/../src/XmlReader/*.c) \
        $$quote($$BASEDIR/../src/XmlReader/*.c++) \
        $$quote($$BASEDIR/../src/XmlReader/*.cc) \
        $$quote($$BASEDIR/../src/XmlReader/*.cpp) \
        $$quote($$BASEDIR/../src/XmlReader/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/*.js) \
        $$quote($$BASEDIR/../assets/Custom/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/ActionItems/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/ActionItems/*.js) \
        $$quote($$BASEDIR/../assets/Custom/ActionItems/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Containers/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Containers/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Containers/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Headers/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Headers/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Headers/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/ListItemComponents/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/ListItemComponents/*.js) \
        $$quote($$BASEDIR/../assets/Custom/ListItemComponents/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/ListViews/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/ListViews/*.js) \
        $$quote($$BASEDIR/../assets/Custom/ListViews/*.qs) \
        $$quote($$BASEDIR/../assets/Images/*.qml) \
        $$quote($$BASEDIR/../assets/Images/*.js) \
        $$quote($$BASEDIR/../assets/Images/*.qs) \
        $$quote($$BASEDIR/../assets/Images/App/*.qml) \
        $$quote($$BASEDIR/../assets/Images/App/*.js) \
        $$quote($$BASEDIR/../assets/Images/App/*.qs) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/*.qml) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/*.js) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/*.qs) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Data/*.qml) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Data/*.js) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Data/*.qs) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Days/*.qml) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Days/*.js) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Days/*.qs) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Days/Plan_01/*.qml) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Days/Plan_01/*.js) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Days/Plan_01/*.qs) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Excercises/*.qml) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Excercises/*.js) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Excercises/*.qs) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Excercises/Plan_01/*.qml) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Excercises/Plan_01/*.js) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Excercises/Plan_01/*.qs) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Plans/*.qml) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Plans/*.js) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Plans/*.qs) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Weeks/*.qml) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Weeks/*.js) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Weeks/*.qs) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Weeks/Plan_01/*.qml) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Weeks/Plan_01/*.js) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Weeks/Plan_01/*.qs) \
        $$quote($$BASEDIR/../assets/JavaScripts/*.qml) \
        $$quote($$BASEDIR/../assets/JavaScripts/*.js) \
        $$quote($$BASEDIR/../assets/JavaScripts/*.qs) \
        $$quote($$BASEDIR/../assets/NavigationPanels/*.qml) \
        $$quote($$BASEDIR/../assets/NavigationPanels/*.js) \
        $$quote($$BASEDIR/../assets/NavigationPanels/*.qs) \
        $$quote($$BASEDIR/../assets/Pages/*.qml) \
        $$quote($$BASEDIR/../assets/Pages/*.js) \
        $$quote($$BASEDIR/../assets/Pages/*.qs) \
        $$quote($$BASEDIR/../assets/Sheets/*.qml) \
        $$quote($$BASEDIR/../assets/Sheets/*.js) \
        $$quote($$BASEDIR/../assets/Sheets/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}_cs.ts) \
    $$quote($${TARGET}.ts)
