# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/Custom/ActionItems/ActionItem_ChangeLayout.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/ActionItem_Download.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/ActionItem_Github.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/ActionItem_GoToBackward.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/ActionItem_GoToForward.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/ActionItem_Home.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/ActionItem_LeaveRating.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/ActionItem_Reload.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/ActionItem_ScrollToBottomList.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/ActionItem_ScrollToBottomWeb.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/ActionItem_ScrollToTopList.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/ActionItem_ScrollToTopWeb.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/ActionItem_SearchMore.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/ActionItem_Share.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/ActionItem_Sort.qml) \
        $$quote($$BASEDIR/assets/Custom/ActivityIndicators/ActivityIndicator_Running.qml) \
        $$quote($$BASEDIR/assets/Custom/ActivityIndicators/CustomActivityIndicator.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Container_B_Margin_1_5.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Container_LR_Margin_1_and_V_Alignment_Center.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Container_LR_Margin_2.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Container_LR_Margin_2_and_HV_Alignment_Center.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Container_TB_Margin_3.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Container_for_DropDowns.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Container_for_Headers.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Container_for_ToggleButtons.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Custom_MainContainer_01.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/MainContainer_for_Pages.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/MainContainer_for_Sheets.qml) \
        $$quote($$BASEDIR/assets/Custom/Dividers/Divider_for_Sort_Settings.qml) \
        $$quote($$BASEDIR/assets/Custom/DropDowns/DropDown_ActionBarVisibility.qml) \
        $$quote($$BASEDIR/assets/Custom/DropDowns/DropDown_ActiveTab.qml) \
        $$quote($$BASEDIR/assets/Custom/DropDowns/DropDown_FollowKeyboardPolicy.qml) \
        $$quote($$BASEDIR/assets/Custom/DropDowns/DropDown_Group.qml) \
        $$quote($$BASEDIR/assets/Custom/DropDowns/DropDown_Order.qml) \
        $$quote($$BASEDIR/assets/Custom/DropDowns/DropDown_PrimaryBaseColor.qml) \
        $$quote($$BASEDIR/assets/Custom/DropDowns/DropDown_PrimaryColor.qml) \
        $$quote($$BASEDIR/assets/Custom/DropDowns/DropDown_ScrollBehavior.qml) \
        $$quote($$BASEDIR/assets/Custom/DropDowns/DropDown_Sort.qml) \
        $$quote($$BASEDIR/assets/Custom/DropDowns/DropDown_TabDelegateActivationPolicy.qml) \
        $$quote($$BASEDIR/assets/Custom/DropDowns/DropDown_TitleBarVisibility.qml) \
        $$quote($$BASEDIR/assets/Custom/DropDowns/DropDown_VisualStyle.qml) \
        $$quote($$BASEDIR/assets/Custom/Headers/CustomHeader_01.qml) \
        $$quote($$BASEDIR/assets/Custom/Headers/CustomHeader_02.qml) \
        $$quote($$BASEDIR/assets/Custom/Headers/CustomHeader_03.qml) \
        $$quote($$BASEDIR/assets/Custom/Headers/CustomHeader_04.qml) \
        $$quote($$BASEDIR/assets/Custom/Headers/Header_AutohideSettings.qml) \
        $$quote($$BASEDIR/assets/Custom/Headers/Header_SortSettings.qml) \
        $$quote($$BASEDIR/assets/Custom/Headers/Header_TabSettings.qml) \
        $$quote($$BASEDIR/assets/Custom/Headers/Header_TesterSettings.qml) \
        $$quote($$BASEDIR/assets/Custom/Headers/Header_ThemeSettings.qml) \
        $$quote($$BASEDIR/assets/Custom/LayoutUpdateHandlers/CustomLayoutUpdateHandlers_for_ListViews.qml) \
        $$quote($$BASEDIR/assets/Custom/ListItemComponents/ListItemComponent_for_Page_BlackWorld.qml) \
        $$quote($$BASEDIR/assets/Custom/ListViews/CustomListView_Info.qml) \
        $$quote($$BASEDIR/assets/Custom/ListViews/CustomListView_Review.qml) \
        $$quote($$BASEDIR/assets/Custom/ListViews/ListView_for_Pages.qml) \
        $$quote($$BASEDIR/assets/Custom/MenuDefinitions/Custom_MenuDefinition.qml) \
        $$quote($$BASEDIR/assets/Custom/MenuDefinitions/Menu_for_SortSettings.qml) \
        $$quote($$BASEDIR/assets/Custom/SystemDialogs/SystemDialog_Warning_01.qml) \
        $$quote($$BASEDIR/assets/Custom/SystemDialogs/SystemDialog_Warning_02.qml) \
        $$quote($$BASEDIR/assets/Custom/SystemProgressToasts/SystemProgressToast_Resetting.qml) \
        $$quote($$BASEDIR/assets/Custom/SystemToasts/SystemToast_Beta.qml) \
        $$quote($$BASEDIR/assets/Custom/SystemToasts/SystemToast_Reset.qml) \
        $$quote($$BASEDIR/assets/Custom/TextAreas/CustomTextArea_01.qml) \
        $$quote($$BASEDIR/assets/Custom/Timers/CustomTimer_for_CustomActivityIndicator.qml) \
        $$quote($$BASEDIR/assets/Custom/Timers/Timer_1000.qml) \
        $$quote($$BASEDIR/assets/Custom/ToggleButtons/ToggleButton_AdaptiveTheme.qml) \
        $$quote($$BASEDIR/assets/Custom/ToggleButtons/ToggleButton_AutohideActionBar.qml) \
        $$quote($$BASEDIR/assets/Custom/ToggleButtons/ToggleButton_AutohideTitleBar.qml) \
        $$quote($$BASEDIR/assets/Custom/ToggleButtons/ToggleButton_ShowBetaOption.qml) \
        $$quote($$BASEDIR/assets/Custom/ToggleButtons/ToggleButton_ShowTabsOnActionBar.qml) \
        $$quote($$BASEDIR/assets/Icons/Icon_AdaptiveTheme_(black).png) \
        $$quote($$BASEDIR/assets/Icons/Icon_AdaptiveTheme_(sky).png) \
        $$quote($$BASEDIR/assets/Icons/Icon_AdaptiveTheme_(sun).png) \
        $$quote($$BASEDIR/assets/Icons/Icon_AdaptiveTheme_(white).png) \
        $$quote($$BASEDIR/assets/Icons/Icon_DevelopmentMode_(gray).png) \
        $$quote($$BASEDIR/assets/Icons/Icon_DevelopmentMode_(pink).png) \
        $$quote($$BASEDIR/assets/Icons/Icon_Download.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_Ext_Browser.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_Github.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_GoToBackward.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_GoToForward.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_GridView.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_Grouping_(false).png) \
        $$quote($$BASEDIR/assets/Icons/Icon_Grouping_(true).png) \
        $$quote($$BASEDIR/assets/Icons/Icon_Home.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_ListView.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_Rate.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_Reload.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_ScrollToBottom.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_ScrollToTop.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_SearchMore.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_Share.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_ShowTabsOnActionbar_(black_false).png) \
        $$quote($$BASEDIR/assets/Icons/Icon_ShowTabsOnActionbar_(black_true).png) \
        $$quote($$BASEDIR/assets/Icons/Icon_ShowTabsOnActionbar_(white_false).png) \
        $$quote($$BASEDIR/assets/Icons/Icon_ShowTabsOnActionbar_(white_true).png) \
        $$quote($$BASEDIR/assets/Icons/Icon_Sort_(hide).png) \
        $$quote($$BASEDIR/assets/Icons/Icon_Sort_(show).png) \
        $$quote($$BASEDIR/assets/Icons/Icon_SortingDate.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_SortingDescription.png) \
        $$quote($$BASEDIR/assets/Icons/Icon_SortingTitle.png) \
        $$quote($$BASEDIR/assets/Images/Image_CustomDivider_(blue).png) \
        $$quote($$BASEDIR/assets/Images/Image_CustomDivider_(red).png) \
        $$quote($$BASEDIR/assets/JavaScripts/JavaScript_Page_BlackWorld.js) \
        $$quote($$BASEDIR/assets/JavaScripts/JavaScript_Page_Github.js) \
        $$quote($$BASEDIR/assets/JavaScripts/JavaScript_Page_Result.js) \
        $$quote($$BASEDIR/assets/JavaScripts/JavaScript_Sheet_Settings.js) \
        $$quote($$BASEDIR/assets/JavaScripts/JavaScript_main.js) \
        $$quote($$BASEDIR/assets/Pages/Page_BlackWorld.qml) \
        $$quote($$BASEDIR/assets/Pages/Page_Github.qml) \
        $$quote($$BASEDIR/assets/Pages/Page_Result.qml) \
        $$quote($$BASEDIR/assets/Sheets/Sheet_Images.qml) \
        $$quote($$BASEDIR/assets/Sheets/Sheet_Settings.qml) \
        $$quote($$BASEDIR/assets/Tabs/Tab_01.qml) \
        $$quote($$BASEDIR/assets/Tabs/Tab_02.qml) \
        $$quote($$BASEDIR/assets/Tabs/Tab_03.qml) \
        $$quote($$BASEDIR/assets/Tabs/Tab_04.qml) \
        $$quote($$BASEDIR/assets/main.qml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/Data/sqldatabase.cpp) \
        $$quote($$BASEDIR/src/Device/display.cpp) \
        $$quote($$BASEDIR/src/Device/hardware.cpp) \
        $$quote($$BASEDIR/src/Settings/settings.cpp) \
        $$quote($$BASEDIR/src/Timer/timer.cpp) \
        $$quote($$BASEDIR/src/WebImageView/webimageview.cpp) \
        $$quote($$BASEDIR/src/XmlReader/xmlreader.cpp) \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/main.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/Data/sqldatabase.hpp) \
        $$quote($$BASEDIR/src/Device/display.hpp) \
        $$quote($$BASEDIR/src/Device/hardware.hpp) \
        $$quote($$BASEDIR/src/Settings/settings.hpp) \
        $$quote($$BASEDIR/src/Timer/timer.hpp) \
        $$quote($$BASEDIR/src/WebImageView/webimageview.hpp) \
        $$quote($$BASEDIR/src/XmlReader/xmlreader.hpp) \
        $$quote($$BASEDIR/src/applicationui.hpp)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../src/Data/*.c) \
        $$quote($$BASEDIR/../src/Data/*.c++) \
        $$quote($$BASEDIR/../src/Data/*.cc) \
        $$quote($$BASEDIR/../src/Data/*.cpp) \
        $$quote($$BASEDIR/../src/Data/*.cxx) \
        $$quote($$BASEDIR/../src/Device/*.c) \
        $$quote($$BASEDIR/../src/Device/*.c++) \
        $$quote($$BASEDIR/../src/Device/*.cc) \
        $$quote($$BASEDIR/../src/Device/*.cpp) \
        $$quote($$BASEDIR/../src/Device/*.cxx) \
        $$quote($$BASEDIR/../src/Settings/*.c) \
        $$quote($$BASEDIR/../src/Settings/*.c++) \
        $$quote($$BASEDIR/../src/Settings/*.cc) \
        $$quote($$BASEDIR/../src/Settings/*.cpp) \
        $$quote($$BASEDIR/../src/Settings/*.cxx) \
        $$quote($$BASEDIR/../src/Timer/*.c) \
        $$quote($$BASEDIR/../src/Timer/*.c++) \
        $$quote($$BASEDIR/../src/Timer/*.cc) \
        $$quote($$BASEDIR/../src/Timer/*.cpp) \
        $$quote($$BASEDIR/../src/Timer/*.cxx) \
        $$quote($$BASEDIR/../src/WebImageView/*.c) \
        $$quote($$BASEDIR/../src/WebImageView/*.c++) \
        $$quote($$BASEDIR/../src/WebImageView/*.cc) \
        $$quote($$BASEDIR/../src/WebImageView/*.cpp) \
        $$quote($$BASEDIR/../src/WebImageView/*.cxx) \
        $$quote($$BASEDIR/../src/XmlReader/*.c) \
        $$quote($$BASEDIR/../src/XmlReader/*.c++) \
        $$quote($$BASEDIR/../src/XmlReader/*.cc) \
        $$quote($$BASEDIR/../src/XmlReader/*.cpp) \
        $$quote($$BASEDIR/../src/XmlReader/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/*.js) \
        $$quote($$BASEDIR/../assets/Custom/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/ActionItems/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/ActionItems/*.js) \
        $$quote($$BASEDIR/../assets/Custom/ActionItems/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/ActivityIndicators/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/ActivityIndicators/*.js) \
        $$quote($$BASEDIR/../assets/Custom/ActivityIndicators/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Containers/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Containers/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Containers/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Dividers/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Dividers/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Dividers/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/DropDowns/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/DropDowns/*.js) \
        $$quote($$BASEDIR/../assets/Custom/DropDowns/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Headers/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Headers/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Headers/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/LayoutUpdateHandlers/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/LayoutUpdateHandlers/*.js) \
        $$quote($$BASEDIR/../assets/Custom/LayoutUpdateHandlers/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/ListItemComponents/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/ListItemComponents/*.js) \
        $$quote($$BASEDIR/../assets/Custom/ListItemComponents/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/ListViews/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/ListViews/*.js) \
        $$quote($$BASEDIR/../assets/Custom/ListViews/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/MenuDefinitions/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/MenuDefinitions/*.js) \
        $$quote($$BASEDIR/../assets/Custom/MenuDefinitions/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/SystemDialogs/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/SystemDialogs/*.js) \
        $$quote($$BASEDIR/../assets/Custom/SystemDialogs/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/SystemProgressToasts/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/SystemProgressToasts/*.js) \
        $$quote($$BASEDIR/../assets/Custom/SystemProgressToasts/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/SystemToasts/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/SystemToasts/*.js) \
        $$quote($$BASEDIR/../assets/Custom/SystemToasts/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/TextAreas/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/TextAreas/*.js) \
        $$quote($$BASEDIR/../assets/Custom/TextAreas/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Timers/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Timers/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Timers/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/ToggleButtons/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/ToggleButtons/*.js) \
        $$quote($$BASEDIR/../assets/Custom/ToggleButtons/*.qs) \
        $$quote($$BASEDIR/../assets/Icons/*.qml) \
        $$quote($$BASEDIR/../assets/Icons/*.js) \
        $$quote($$BASEDIR/../assets/Icons/*.qs) \
        $$quote($$BASEDIR/../assets/Images/*.qml) \
        $$quote($$BASEDIR/../assets/Images/*.js) \
        $$quote($$BASEDIR/../assets/Images/*.qs) \
        $$quote($$BASEDIR/../assets/JavaScripts/*.qml) \
        $$quote($$BASEDIR/../assets/JavaScripts/*.js) \
        $$quote($$BASEDIR/../assets/JavaScripts/*.qs) \
        $$quote($$BASEDIR/../assets/Pages/*.qml) \
        $$quote($$BASEDIR/../assets/Pages/*.js) \
        $$quote($$BASEDIR/../assets/Pages/*.qs) \
        $$quote($$BASEDIR/../assets/Sheets/*.qml) \
        $$quote($$BASEDIR/../assets/Sheets/*.js) \
        $$quote($$BASEDIR/../assets/Sheets/*.qs) \
        $$quote($$BASEDIR/../assets/Tabs/*.qml) \
        $$quote($$BASEDIR/../assets/Tabs/*.js) \
        $$quote($$BASEDIR/../assets/Tabs/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
