# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/Custom/ActionItems/Custom_ActionItem_01.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/Custom_ActionItem_02.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/Custom_ActionItem_03.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/Custom_ActionItem_04.qml) \
        $$quote($$BASEDIR/assets/Custom/ActionItems/Custom_ActionItem_05.qml) \
        $$quote($$BASEDIR/assets/Custom/Buttons/Custom_Button_01.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Custom_Container_01.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Custom_Container_02.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Custom_Container_03.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Custom_MainContainer.qml) \
        $$quote($$BASEDIR/assets/Custom/Headers/Custom_Header_01.qml) \
        $$quote($$BASEDIR/assets/Custom/ImageButtons/Custom_ImageButton_01.qml) \
        $$quote($$BASEDIR/assets/Custom/ImageButtons/Custom_ImageButton_02.qml) \
        $$quote($$BASEDIR/assets/Custom/ImageButtons/Custom_ImageButton_03.qml) \
        $$quote($$BASEDIR/assets/Custom/ImageButtons/Custom_ImageButton_04.qml) \
        $$quote($$BASEDIR/assets/Custom/ImageButtons/Custom_ImageButton_05.qml) \
        $$quote($$BASEDIR/assets/Custom/ImageButtons/Custom_ImageButton_06.qml) \
        $$quote($$BASEDIR/assets/Custom/ImageButtons/Custom_ImageButton_07.qml) \
        $$quote($$BASEDIR/assets/Custom/ImageButtons/Custom_ImageButton_08.qml) \
        $$quote($$BASEDIR/assets/Custom/ImageButtons/Custom_ImageButton_09.qml) \
        $$quote($$BASEDIR/assets/Custom/ImageButtons/Custom_ImageButton_10.qml) \
        $$quote($$BASEDIR/assets/Custom/ImageButtons/Custom_ImageButton_11.qml) \
        $$quote($$BASEDIR/assets/Custom/ImageButtons/Custom_ImageButton_12.qml) \
        $$quote($$BASEDIR/assets/Custom/ImageButtons/Custom_ImageButton_13.qml) \
        $$quote($$BASEDIR/assets/Custom/ImageButtons/Custom_ImageButton_14.qml) \
        $$quote($$BASEDIR/assets/Custom/Menu/Custom_MenuDefinition.qml) \
        $$quote($$BASEDIR/assets/Custom/Sliders/Custom_Slider_01.qml) \
        $$quote($$BASEDIR/assets/Custom/StandardListItems/Custom_StandardListItem_01.qml) \
        $$quote($$BASEDIR/assets/Custom/SystemToasts/Custom_SystemToast_01.qml) \
        $$quote($$BASEDIR/assets/Custom/SystemToasts/Custom_SystemToast_02.qml) \
        $$quote($$BASEDIR/assets/Custom/TextFields/Custom_TextField_01.qml) \
        $$quote($$BASEDIR/assets/Custom/Timers/Custom_Timer_01.qml) \
        $$quote($$BASEDIR/assets/Custom/Timers/Custom_Timer_02.qml) \
        $$quote($$BASEDIR/assets/Custom/TitleBars/Custom_TitleBar_01.qml) \
        $$quote($$BASEDIR/assets/Custom/TitleBars/Custom_TitleBar_02.qml) \
        $$quote($$BASEDIR/assets/Custom/WebImagesView/Custom_WebImageView_01.qml) \
        $$quote($$BASEDIR/assets/CustomMerged/CustomMerged_FceButtons.qml) \
        $$quote($$BASEDIR/assets/CustomMerged/CustomMerged_ImageButtons_01.qml) \
        $$quote($$BASEDIR/assets/CustomMerged/CustomMerged_ImageButtons_02.qml) \
        $$quote($$BASEDIR/assets/CustomMerged/CustomMerged_NowPlaying.qml) \
        $$quote($$BASEDIR/assets/CustomMerged/CustomMerged_VolumeSlider.qml) \
        $$quote($$BASEDIR/assets/Images/Image_Back.png) \
        $$quote($$BASEDIR/assets/Images/Image_Background_(dark).png) \
        $$quote($$BASEDIR/assets/Images/Image_Blank.png) \
        $$quote($$BASEDIR/assets/Images/Image_ButtonMain_(up).png) \
        $$quote($$BASEDIR/assets/Images/Image_Button_(down).png) \
        $$quote($$BASEDIR/assets/Images/Image_Button_(up).png) \
        $$quote($$BASEDIR/assets/Images/Image_Context.png) \
        $$quote($$BASEDIR/assets/Images/Image_Home.png) \
        $$quote($$BASEDIR/assets/Images/Image_ImageButton_07.png) \
        $$quote($$BASEDIR/assets/Images/Image_ImageButton_08.png) \
        $$quote($$BASEDIR/assets/Images/Image_ImageButton_09.png) \
        $$quote($$BASEDIR/assets/Images/Image_ImageButton_10.png) \
        $$quote($$BASEDIR/assets/Images/Image_ImageButton_11.png) \
        $$quote($$BASEDIR/assets/Images/Image_Poster_(empty).png) \
        $$quote($$BASEDIR/assets/Images/Image_Volume_(down).png) \
        $$quote($$BASEDIR/assets/Images/Image_Volume_(up).png) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Data/Data.xml) \
        $$quote($$BASEDIR/assets/JSON + SQL + XML/Data/Database.db) \
        $$quote($$BASEDIR/assets/JavaScripts/CustomMerged_NowPlaying.js) \
        $$quote($$BASEDIR/assets/JavaScripts/JavaScript_Page_Remote.js) \
        $$quote($$BASEDIR/assets/JavaScripts/JavaScript_main.js) \
        $$quote($$BASEDIR/assets/Pages/Page_Remote.qml) \
        $$quote($$BASEDIR/assets/Sheets/Sheet.qml) \
        $$quote($$BASEDIR/assets/Sheets/Sheet_Settings.qml) \
        $$quote($$BASEDIR/assets/XXX/AaaBbb_titel.qml) \
        $$quote($$BASEDIR/assets/XXX/Copy_Custom_ImageButton_03.qml) \
        $$quote($$BASEDIR/assets/XXX/DOWN.qml) \
        $$quote($$BASEDIR/assets/XXX/aa.qml) \
        $$quote($$BASEDIR/assets/XXX/aaa.qml) \
        $$quote($$BASEDIR/assets/XXX/aaaa.qml) \
        $$quote($$BASEDIR/assets/XXX/aaaaa.qml) \
        $$quote($$BASEDIR/assets/XXX/custom_slider.qml) \
        $$quote($$BASEDIR/assets/XXX/custommerged_now_playing.qml) \
        $$quote($$BASEDIR/assets/XXX/custommerged_volume.qml) \
        $$quote($$BASEDIR/assets/information.qml) \
        $$quote($$BASEDIR/assets/main.qml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/Settings/settings.cpp) \
        $$quote($$BASEDIR/src/SqlDatabase/sqldatabase.cpp) \
        $$quote($$BASEDIR/src/Timer/timer.cpp) \
        $$quote($$BASEDIR/src/WebImageView/webimageview.cpp) \
        $$quote($$BASEDIR/src/XmlReader/xmlreader.cpp) \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/main.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/Settings/settings.hpp) \
        $$quote($$BASEDIR/src/SqlDatabase/sqldatabase.hpp) \
        $$quote($$BASEDIR/src/Timer/timer.hpp) \
        $$quote($$BASEDIR/src/WebImageView/webimageview.hpp) \
        $$quote($$BASEDIR/src/XmlReader/xmlreader.hpp) \
        $$quote($$BASEDIR/src/applicationui.hpp)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../src/Settings/*.c) \
        $$quote($$BASEDIR/../src/Settings/*.c++) \
        $$quote($$BASEDIR/../src/Settings/*.cc) \
        $$quote($$BASEDIR/../src/Settings/*.cpp) \
        $$quote($$BASEDIR/../src/Settings/*.cxx) \
        $$quote($$BASEDIR/../src/SqlDatabase/*.c) \
        $$quote($$BASEDIR/../src/SqlDatabase/*.c++) \
        $$quote($$BASEDIR/../src/SqlDatabase/*.cc) \
        $$quote($$BASEDIR/../src/SqlDatabase/*.cpp) \
        $$quote($$BASEDIR/../src/SqlDatabase/*.cxx) \
        $$quote($$BASEDIR/../src/Timer/*.c) \
        $$quote($$BASEDIR/../src/Timer/*.c++) \
        $$quote($$BASEDIR/../src/Timer/*.cc) \
        $$quote($$BASEDIR/../src/Timer/*.cpp) \
        $$quote($$BASEDIR/../src/Timer/*.cxx) \
        $$quote($$BASEDIR/../src/WebImageView/*.c) \
        $$quote($$BASEDIR/../src/WebImageView/*.c++) \
        $$quote($$BASEDIR/../src/WebImageView/*.cc) \
        $$quote($$BASEDIR/../src/WebImageView/*.cpp) \
        $$quote($$BASEDIR/../src/WebImageView/*.cxx) \
        $$quote($$BASEDIR/../src/XmlReader/*.c) \
        $$quote($$BASEDIR/../src/XmlReader/*.c++) \
        $$quote($$BASEDIR/../src/XmlReader/*.cc) \
        $$quote($$BASEDIR/../src/XmlReader/*.cpp) \
        $$quote($$BASEDIR/../src/XmlReader/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/*.js) \
        $$quote($$BASEDIR/../assets/Custom/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/ActionItems/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/ActionItems/*.js) \
        $$quote($$BASEDIR/../assets/Custom/ActionItems/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Buttons/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Buttons/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Buttons/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Containers/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Containers/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Containers/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Headers/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Headers/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Headers/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/ImageButtons/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/ImageButtons/*.js) \
        $$quote($$BASEDIR/../assets/Custom/ImageButtons/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Menu/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Menu/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Menu/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Sliders/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Sliders/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Sliders/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/StandardListItems/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/StandardListItems/*.js) \
        $$quote($$BASEDIR/../assets/Custom/StandardListItems/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/SystemToasts/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/SystemToasts/*.js) \
        $$quote($$BASEDIR/../assets/Custom/SystemToasts/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/TextFields/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/TextFields/*.js) \
        $$quote($$BASEDIR/../assets/Custom/TextFields/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Timers/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Timers/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Timers/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/TitleBars/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/TitleBars/*.js) \
        $$quote($$BASEDIR/../assets/Custom/TitleBars/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/WebImagesView/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/WebImagesView/*.js) \
        $$quote($$BASEDIR/../assets/Custom/WebImagesView/*.qs) \
        $$quote($$BASEDIR/../assets/CustomMerged/*.qml) \
        $$quote($$BASEDIR/../assets/CustomMerged/*.js) \
        $$quote($$BASEDIR/../assets/CustomMerged/*.qs) \
        $$quote($$BASEDIR/../assets/Images/*.qml) \
        $$quote($$BASEDIR/../assets/Images/*.js) \
        $$quote($$BASEDIR/../assets/Images/*.qs) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/*.qml) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/*.js) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/*.qs) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Data/*.qml) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Data/*.js) \
        $$quote($$BASEDIR/../assets/JSON + SQL + XML/Data/*.qs) \
        $$quote($$BASEDIR/../assets/JavaScripts/*.qml) \
        $$quote($$BASEDIR/../assets/JavaScripts/*.js) \
        $$quote($$BASEDIR/../assets/JavaScripts/*.qs) \
        $$quote($$BASEDIR/../assets/NavigationsPanes/*.qml) \
        $$quote($$BASEDIR/../assets/NavigationsPanes/*.js) \
        $$quote($$BASEDIR/../assets/NavigationsPanes/*.qs) \
        $$quote($$BASEDIR/../assets/Pages/*.qml) \
        $$quote($$BASEDIR/../assets/Pages/*.js) \
        $$quote($$BASEDIR/../assets/Pages/*.qs) \
        $$quote($$BASEDIR/../assets/Sheets/*.qml) \
        $$quote($$BASEDIR/../assets/Sheets/*.js) \
        $$quote($$BASEDIR/../assets/Sheets/*.qs) \
        $$quote($$BASEDIR/../assets/XXX/*.qml) \
        $$quote($$BASEDIR/../assets/XXX/*.js) \
        $$quote($$BASEDIR/../assets/XXX/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
