# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/Custom/ActionItems/Custom_ActionItem_01.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Custom_Container_01.qml) \
        $$quote($$BASEDIR/assets/Custom/Containers/Custom_MainContainer.qml) \
        $$quote($$BASEDIR/assets/Custom/Headers/Custom_Header_01.qml) \
        $$quote($$BASEDIR/assets/Custom/HomeScreens/Custom_HomeScreen_01.qml) \
        $$quote($$BASEDIR/assets/Custom/Menu/Custom_Menu.qml) \
        $$quote($$BASEDIR/assets/Custom/Sliders/Custom_Slider_01.qml) \
        $$quote($$BASEDIR/assets/Custom/SystemToasts/Custom_SystemToast_01.qml) \
        $$quote($$BASEDIR/assets/Icons/icon_add.png) \
        $$quote($$BASEDIR/assets/Images/image_invisible.png) \
        $$quote($$BASEDIR/assets/JavaScripts/JavaScript_Page.js) \
        $$quote($$BASEDIR/assets/Pages/Page.qml) \
        $$quote($$BASEDIR/assets/main.qml)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/*.js) \
        $$quote($$BASEDIR/../assets/Custom/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/ActionItems/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/ActionItems/*.js) \
        $$quote($$BASEDIR/../assets/Custom/ActionItems/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Containers/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Containers/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Containers/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Headers/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Headers/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Headers/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/HomeScreens/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/HomeScreens/*.js) \
        $$quote($$BASEDIR/../assets/Custom/HomeScreens/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Menu/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Menu/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Menu/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/Sliders/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/Sliders/*.js) \
        $$quote($$BASEDIR/../assets/Custom/Sliders/*.qs) \
        $$quote($$BASEDIR/../assets/Custom/SystemToasts/*.qml) \
        $$quote($$BASEDIR/../assets/Custom/SystemToasts/*.js) \
        $$quote($$BASEDIR/../assets/Custom/SystemToasts/*.qs) \
        $$quote($$BASEDIR/../assets/Icons/*.qml) \
        $$quote($$BASEDIR/../assets/Icons/*.js) \
        $$quote($$BASEDIR/../assets/Icons/*.qs) \
        $$quote($$BASEDIR/../assets/Images/*.qml) \
        $$quote($$BASEDIR/../assets/Images/*.js) \
        $$quote($$BASEDIR/../assets/Images/*.qs) \
        $$quote($$BASEDIR/../assets/JavaScripts/*.qml) \
        $$quote($$BASEDIR/../assets/JavaScripts/*.js) \
        $$quote($$BASEDIR/../assets/JavaScripts/*.qs) \
        $$quote($$BASEDIR/../assets/Pages/*.qml) \
        $$quote($$BASEDIR/../assets/Pages/*.js) \
        $$quote($$BASEDIR/../assets/Pages/*.qs)

}

TRANSLATIONS = $$quote($${TARGET}.ts)
